### ISSUE TITLE
Error in commit references unknown v${version}.tar.gz

### ISSUE THREAD

**Issue by mwbringmann** [power-ras/lsvpd#1]
Error in commit b07ac59de9792120a434924c9c52341fe73a13cf produces the following error message for rpmbuild:

[root@RHEL8 lsvpd]# rpmbuild -ba ~/rpmbuild/SPECS/lsvpd.spec
error: Bad source: /root/rpmbuild/SOURCES/v1.7.10.tar.gz: No such file or directory
[root@RHEL8 lsvpd]# 

The commit includes the change,

-Source:                https://github.com/power-ras/lsvpd.git
+Source:                https://github.com/power-ras/%{name}/archive/v%{version}.tar.gz

which should have been,

-Source:                https://github.com/power-ras/lsvpd.git
+Source:                https://github.com/power-ras/%{name}/archive/lsvpd-%{version}.tar.gz

to match the file generated by the 'make dist-gzip' operation.

**Comment by hegdevasant** [comment]
Thanks for the report. I will fix it next week.

-Vasant
